### ISSUE TITLE
Generated notifications should be logged in a seperate log file 

### ISSUE THREAD

**Issue by Steffengreiner** [qbicsoftware/sample-notificator-cli#7]
Currently the `sample-notificator-cli` has no logging service implemented, this makes handling any errors occuring in the use cases hard to track and debug. 

**Possible solution** 
Establish a dedicated log file, which solely tracks the resulting notifications and exit codes from the `sample-notificator-cli.`
According to MS, a similiar solution is already established for the sampletracking-service on our servers. 

**Additional Information**
Each process call of the mailutil service is automatically logged in the maillog on our servers. 
However the question would be, if this should also be outsourced to a dedicated log solely for the `sample-notification service`

**Comment by jenniferboedker** [comment]
solved with #28
